### ISSUE TITLE
Create the 3 courses pages

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#10]
Try to copy the layout. Dont go too much in detail but use the position: sticky left sidebar and add [Bootstraps scrollspy](https://getbootstrap.com/docs/4.1/components/scrollspy/#example-with-nested-nav)

https://digitalcareerinstitute.org/kurse/jahreskurs/
https://digitalcareerinstitute.org/kurse/orientierungskurs/
https://digitalcareerinstitute.org/kurse/einzelcoaching/

**Comment by shteyn** [comment]
The "One Year Page" - done
Link: http://localhost:3000/courses

**Comment by shteyn** [comment]
Closed by #31

**Comment by shteyn** [comment]
Closed by #31
