### ISSUE TITLE
Add devise pixelratio meta tag

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#110]
This looks like shit - it should render on a iPhone with the corresponding pixel-aspect-ratio.
<img width="454" alt="screenshot 2018-11-14 at 21 08 46" src="https://user-images.githubusercontent.com/6317641/48509474-8370c180-e851-11e8-9591-e25ff1cac88a.png">

**Comment by shteyn** [comment]
Issue done by #133
