### ISSUE TITLE
Admin stories view is broken.

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#111]
ImagePath in `views/mixings/storyList.pug` must be absolute.
In this ticket there could be also the whole admin section a bit refurbished.

<img width="1703" alt="screenshot 2018-11-14 at 21 11 38" src="https://user-images.githubusercontent.com/6317641/48509626-e8c4b280-e851-11e8-9bb5-b244374e7bf7.png">

**Comment by shteyn** [comment]
closed by #146
