### ISSUE TITLE
Create SocialMedia sharing preview and SEO optimization v1 statuic

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#119]
When linking our website per FB or so, it should render a nice preview picture. In this ticket we can also provide proper meta tags for google.

**Comment by spielhoelle** [comment]
<img width="940" alt="screenshot 2018-11-19 at 10 31 44" src="https://user-images.githubusercontent.com/6317641/48698010-553f0900-ebe6-11e8-8279-8f9ff27b69bc.png">

**Comment by spielhoelle** [comment]
Make it static first like in the screenshot

**Comment by shteyn** [comment]
issue closed by #145
