### ISSUE TITLE
Clean up pug and css structure

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#120]

**Comment by spielhoelle** [comment]
CSS: make css to scss. Eighter require them into the `style.scss` or put them together into one. Just clean a bit
PUG: meaningful naming-convention that we avoid things like `page.pug` `pages.pug`.. Maybe `landingpage.pug` Review the landingpagemixins

**Comment by shteyn** [comment]
Working on merging all files into style.scss

**Comment by shteyn** [comment]
CSS structure is done.
Pull request #128
