### ISSUE TITLE
Fix navi

### ISSUE THREAD

**Issue by shteyn** [DigitalCareerInstitute/marketing-website#150]
Brackets just on desktop and on first hirachy.
![screenshot at 09-52-43](https://user-images.githubusercontent.com/37113074/49210137-95f40a80-f3bc-11e8-9564-333f63add2c4.png)

**Comment by shteyn** [comment]
@pilartorr - the brackets all over the navigation bar are still broken.

**Comment by spielhoelle** [comment]
closed by #191
