### ISSUE TITLE
Create the contents of Data Privacy in the contact form

### ISSUE THREAD

**Issue by pilartorr** [DigitalCareerInstitute/marketing-website#157]

**Comment by pilartorr** [comment]
![screenshot from 2018-11-30 14-45-25](https://user-images.githubusercontent.com/35297742/49293045-3296d500-f4af-11e8-9e35-d0d88be6ea1d.png)

**Comment by pilartorr** [comment]
https://digitalcareerinstitute.org/en/data-privacy/

**Comment by shteyn** [comment]
issue closed by #183
