### ISSUE TITLE
Landingpage | Click on contact page scrolls down

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#17]
<img width="614" alt="screen shot 2018-10-15 at 18 57 48" src="https://user-images.githubusercontent.com/6317641/46965859-3fe93300-d0ac-11e8-9d4d-f210b68ad7b8.png">

Click on the right CTA and your screen should go to the contact form
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by shteyn** [comment]
Added simple id div scroll.

**Comment by shteyn** [comment]
Fixed by #51
