### ISSUE TITLE
Change contact form behavior for events

### ISSUE THREAD

**Issue by pilartorr** [DigitalCareerInstitute/marketing-website#172]
when you click in a event, appears this pop-window like so contact-form

**Comment by shteyn** [comment]
1. When you click on the "Contact Us" in navbar the location is pre-selected.
2. When you submit a contact form from Company tours, the lable is added to the final admin view.

We want the same behavior on the contact form that comes from event:
1. Location pre-selected
2, Label that the request comes from the event
/home/dci/DCI-Marketing/marketing-website/routes/index.js:59

**Comment by shteyn** [comment]
@spielhoelle - we need to discuss again the events behavior.  Maybe we need to remove the "Contact From" modal on click and redirect to the single event page.

**Comment by shteyn** [comment]
not relevant since the whole structure has been changes for the single event.
Issue closed
