### ISSUE TITLE
Repair frontend contact form

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#19]
Our contact model currently has
```
    name: String,
    email: String,
    body: String,
```
Now there is just a email form.

It was working in this [version](https://github.com/DigitalCareerInstitute/marketing-website/commit/0b8aacf5869ab43b6e84add394773a81fb6c7296?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8), **please put that version back** (inputs, ids, names and form-action)

**Comment by shteyn** [comment]
Fixed by #51
