### ISSUE TITLE
Post mixin not found

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#21]
http://localhost:4000/posts

**Comment by shteyn** [comment]
I will check tomorrow with another guys. Maybe they have an older repo. I don't remember, that I deleted some files.

**Comment by spielhoelle** [comment]
But maybe its not really linked? On current master its not working :(

<img width="1176" alt="screen shot 2018-10-15 at 20 00 23" src="https://user-images.githubusercontent.com/6317641/46968997-079a2280-d0b5-11e8-99eb-d29ab026e637.png">

**Comment by shteyn** [comment]
Need some time. Checking. Usually it is some spacing issue with pug

**Comment by shteyn** [comment]
Can you please tell me, what you exactly trying to do.

**Comment by shteyn** [comment]
Sorry, but I cant understand.  I cloned the repo and I can see everything on port 3000. I don't have any issues. And I didn't changed any routing.

there is also in index.js
`app.listen(port, () => console.log(`Example app listening on port ${port}!`));`

**Comment by spielhoelle** [comment]
Here is the version in the live bug https://dci.tmy.io/posts

**Comment by shteyn** [comment]
Got you. I will take a look.

**Comment by spielhoelle** [comment]
https://media.giphy.com/media/lblRk4JSkNJkY/giphy.gif

**Comment by shteyn** [comment]
Fuc.,l,ö,öööö.

I commented in layout.pug the following.
include mixins/postlist
include mixins/contactform

Didn't knew, that we need it now. Sorryyyyyy
Do you want to change it or me to push it?

**Comment by spielhoelle** [comment]
Amazing ! Works https://dci.tmy.io/posts
