### ISSUE TITLE
Landingpage Events should show less text => Excerpt of the whole

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#212]
<img width="438" alt="screenshot 2018-12-11 at 12 31 18" src="https://user-images.githubusercontent.com/6317641/49797751-abfcb600-fd40-11e8-98a7-4c4491a55613.png">

**Comment by shteyn** [comment]
The event text should contain 1 sentence:
Mabye: text overflow ellipsis 
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
