### ISSUE TITLE
Remove /courses route, view, controller action

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#213]
We just want to show single courses and not a set of all courses. We will just scroll down on the landingpage to the courses section

**Comment by shteyn** [comment]
1. When you click on the "Browse courses" btn on the header it scrolls to the "our courses".
2. remove btn "browse courses" from "our courses"
3. remove get courses from courseControler and courses.js "router.get (coursesController)"

**Comment by shteyn** [comment]
The last task is to redirect directly from the landing page to the relevant course page, while clicking on the course link under "Our courses"

**Comment by shteyn** [comment]
@spielhoelle  - I think this ticket is already done. Please confirm.
