### ISSUE TITLE
Fix wrong typoraphy

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#237]
![screenshot from 2019-01-31 13-34-03](https://user-images.githubusercontent.com/6317641/52054856-17534f00-255e-11e9-859c-4e49cb7626e5.png)

**Comment by shteyn** [comment]
We need to review all css styles:
1. remove duplicate classes or merge: like body, fonts, colors, etc.

**Comment by shteyn** [comment]
related to #241
