### ISSUE TITLE
eventbrite implemented checkout for a single event

### ISSUE THREAD

**Issue by shteyn** [DigitalCareerInstitute/marketing-website#245]

**Comment by shteyn** [comment]
Based on discussion with Mozamel, he wants to implement the eventbrite's checkout for a single event.
@spielhoelle - We need to check how we can implement it.

**Comment by spielhoelle** [comment]
What means checkout? To subscribe to an event directly on our page?

**Comment by shteyn** [comment]
PR #246 implemented simple redirection to eventbrite on click. 
Need to be discussed if we want to integrate eventbrite checkout onsite
