### ISSUE TITLE
courses images should allow SVG filetype

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#248]
admin courses controller `file.mimetype`

**Comment by shteyn** [comment]
const multer = require('multer')

module.exports = multer({
 storage: multer.diskStorage({}),
 fileFilter: (req, file, callback) => {
   if (!file.mimetype.match(/jpeg|jpg|png|gif/)) {
     callback(new Error('This is not supported'), false)
     return
   }
   callback(null, true)
 }
})

**Comment by shteyn** [comment]
Multiple file extensions are possible
