### ISSUE TITLE
No upload images for btn in admin page for edit course page

### ISSUE THREAD

**Issue by shteyn** [DigitalCareerInstitute/marketing-website#256]

**Comment by shteyn** [comment]
![uploadimg_bug](https://user-images.githubusercontent.com/37113074/53171327-bc53cb80-35e2-11e9-86a6-53727bd5e3f7.png)

**Comment by shteyn** [comment]
![uploadimg_bug](https://user-images.githubusercontent.com/37113074/53171342-c70e6080-35e2-11e9-82a3-815897ee4abd.png)

**Comment by spielhoelle** [comment]
Courses should just have 3 features, the actual record in the mongo db had 5. 
I manually deleted 2 each. Now there are just three.
