### ISSUE TITLE
Eventbrite-Events preview image size

### ISSUE THREAD

**Issue by oliverwebr** [DigitalCareerInstitute/marketing-website#272]
The current landing page has a size of 6mb because eventbrite delivers the preview image in its original resolution. There is probably a parameter avoid this.

<img width="1331" alt="Devtools screenshot showing the issue" src="https://user-images.githubusercontent.com/3374276/63939865-8c412580-ca68-11e9-98cb-553e6509965f.png">

**Comment by spielhoelle** [comment]
Solved by https://github.com/DigitalCareerInstitute/marketing-website/commit/3444fb98ab2aa6f9c9399607cc401cd7d7a411d2#diff-2b078b2d1c50ceb26723798768666f45R72
