### ISSUE TITLE
TTFB really high

### ISSUE THREAD

**Issue by oliverwebr** [DigitalCareerInstitute/marketing-website#273]
The TTFB (Time to first byte) is currently 2.15 seconds. It would worth to investigate if this server or app related.

<img width="1258" alt="Screenshot of devtools, showing the network tab waterfall diagram." src="https://user-images.githubusercontent.com/3374276/63940244-623c3300-ca69-11e9-863f-d7e61a0854f9.png">

**Comment by spielhoelle** [comment]
I think the problem is here. ‘Promise.all’ could resolve that verbose loop.
PRs are welcome <3

https://github.com/DigitalCareerInstitute/marketing-website/blob/master/controllers/IndexController.js#L24

**Comment by oliverwebr** [comment]
Just checked and it is not much lower TTFB for other pages as well e.g. Imprint - 1.45 s
<img width="675" alt="Screenshot 2019-09-06 at 13 57 35" src="https://user-images.githubusercontent.com/3374276/64426269-6d691180-d0ae-11e9-939b-3b450aebcce3.png">

**Comment by spielhoelle** [comment]
Moved to [trello](https://trello.com/c/EZDl28Qb)
