### ISSUE TITLE
Course view does not show location.name

### ISSUE THREAD

**Issue by kgrhartlage** [DigitalCareerInstitute/marketing-website#310]
👋

![Screen Shot 2020-04-12 at 21 06 01](https://user-images.githubusercontent.com/42832087/79077395-a0891880-7d01-11ea-9b4f-919b3a1aff76.png)

**Comment by spielhoelle** [comment]
Thanks for the issues - that’s the spirit we need. Our dev team will move it into the pipeline ASAP.
PS: Pullrequests are highly welcomed ;)

**Comment by spielhoelle** [comment]
fixed by e27375934573cccc0a8f343582d77918d3c5b6af and will be scheduled in the next deployment
