### ISSUE TITLE
Phone form field has confusing placeholder

### ISSUE THREAD

**Issue by kgrhartlage** [DigitalCareerInstitute/marketing-website#311]
Since the label is `sr-only` it took me a couple seconds to figure out that I'm supposed to enter my phone number here. Changing the placeholder to something like "0170-123456789" or "Phone Number" would remove this ambiguity.

Additionally, this field could be placed after "Name" and "Email", since they all represent contact information. Separating them with the "Message" field seems odd.

**Comment by spielhoelle** [comment]
I remember that we actively designed it like that order. But a re-evaluation is often a good idea.

**Comment by spielhoelle** [comment]
Fixed by e52570f9ab2977fb1b87585b5e8d2d0b9c8a2c6b
