### ISSUE TITLE
Input padding on contact form cuts of descenders

### ISSUE THREAD

**Issue by kgrhartlage** [DigitalCareerInstitute/marketing-website#312]
![Screen Shot 2020-04-12 at 21 26 52](https://user-images.githubusercontent.com/42832087/79077882-c368fc00-7d04-11ea-9db8-68e15efc6503.png)

**Comment by spielhoelle** [comment]
Valid - will fix it soon

**Comment by spielhoelle** [comment]
fixed by c1161cee309b97aac272e388bad34cd0f5914349 and will be scheduled in the next deployment
