### ISSUE TITLE
File upload fail

### ISSUE THREAD

**Issue by Leon-Arno** [DigitalCareerInstitute/marketing-website#332]
Can't upload course overview PDF file. Size of document = 1.4MB
<img width="474" alt="Screenshot" src="https://user-images.githubusercontent.com/8118254/86460459-b585ae80-bd28-11ea-815f-f2bf9f4a8113.png">

**Comment by spielhoelle** [comment]
Fixed by [f8c7e4c](https://github.com/DigitalCareerInstitute/infrastructure/commit/f8c7e4c6f79c3e2c7f58068b69de6f761d93df3e) in [infrastructure repo](https://github.com/DigitalCareerInstitute/infrastructure)
