### ISSUE TITLE
ReferenceError on 'Logout'

### ISSUE THREAD

**Issue by Leon-Arno** [DigitalCareerInstitute/marketing-website#333]
<img width="1244" alt="Screenshot 2020-07-08 at 13 45 19" src="https://user-images.githubusercontent.com/8118254/86921221-10eddd00-c12b-11ea-81da-b6d70962adff.png">

**Comment by spielhoelle** [comment]
Fixed by 559e75daf1f2f9e1982f37ac91a4f972224df6a4
