### ISSUE TITLE
Display events as simple cards

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#40]
3 on the landingpage 
~ 10 on the events page

**Comment by spielhoelle** [comment]
Use a location list like this like
Hamburg
Berlin
Köln 

Like this https://gedd.ski/post/position-sticky/

**Comment by shteyn** [comment]
Issue related to #104

**Comment by shteyn** [comment]
closed by #104

**Comment by shteyn** [comment]
closed by #104
