### ISSUE TITLE
Paths broken without absolute beginning `/`

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#54]
![screen shot 2018-10-29 at 16 37 30](https://user-images.githubusercontent.com/6317641/47661276-03800180-db99-11e8-8f98-61d7cbc658e6.png)

Line [19 and 20](https://github.com/DigitalCareerInstitute/marketing-website/commit/1ab38c377ade2c6166858d13c00848bc1356da51#diff-78c12f5adc1848d13b1c6f07055d996eR19) killed our live assets paths. Revert this two lines please.

**Comment by shteyn** [comment]
Closed by #56
