### ISSUE TITLE
Add the corporate color + fonts

### ISSUE THREAD

**Issue by spielhoelle** [DigitalCareerInstitute/marketing-website#62]

**Comment by pilartorr** [comment]
Colors for the website:
blue: #1d3b8b 
orange: #e38419
white-background: #f8f7f7
shadow-3D: #bfbebe

Typography:
initial-arrow => color: #939393
                   => font-family: Yanone Kaffeesatz (light)
                   => maybe (16px)
rest of the page =>font-family Century Gothic Pro (bold / regular)
