### ISSUE TITLE
Enhance Popup

### ISSUE THREAD

**Issue by shteyn** [DigitalCareerInstitute/marketing-website#78]
1. Enhance Popup input requirement #73
 2. Use only 1 template #53 
3. If opened oi submitted store cookies on local storage

**Comment by spielhoelle** [comment]
Popup should not close on Send!. It should actually send the contact form and the new contact should be visible at http://localhost:4000/admin/contacts

**Comment by shteyn** [comment]
1. Enhance Popup input requirement #73: the issue was triggered by additional contact form that was used for hided  popup modal. The issue has been fixed by using one contact form template. See bullet 2.

2. Use only 1 template #53: index.pug has been extended with the same contact form but under the "modal" class. 

3. If opened oi submitted store cookies on local storage. 

   - The "frontend.js" has been updated with the setTimeout function for 5 sec to popup the contact form
   - Localstorage is storing an item + Boolean to track the popup state. the modal will be shown after 5sec 
      only once. In order to see the modal again clear the localStorage. 

4. The "TermsofService" checkbox has been set as required. 
5. "location-checkbox" has been changed based on the "TermsofService" input in order to avoid scrolling the window after you trying to click checkbox in popup modal. 

After all changes user is able to send a form via the "modal" contact form and not modal with all restrictions.
